# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nqS9xCn2mLwZ14UM09778koLSD_q1DNT
"""

print("hello world")